#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

dir=${PWD##*/}

# Make sure we have access to some OpenFOAM scripts
module load openfoam/openfoam-6.0-openmpi-3.1.0-gcc-7.1.0
source $foamDotFile
export WM_LABEL_SIZE=64

echo "--------"
echo "Cleaning ${dir}s ..."
echo "Removing backup files"
find . -type f \( -name "*~" -o -name "*.bak" \) -exec rm {} \;
find . \( -name core -o -name 'core.[1-9]*' \) -exec rm {} \;
find . \( -name '*.pvs' -o -name '*.OpenFOAM' \) -exec rm {} \;
rm logs testLoopReport > /dev/null 2>&1

foamCleanTutorials cases

echo "--------"

#------------------------------------------------------------------------------
